### ISSUE TITLE
help for file

### ISSUE THREAD

**Issue by tongyt1225** [KnottLab/bladder-snSeq#1]
Hello, I'm very interested in the analysis of pyscenic in your article, so I'd like to know if you can provide the file hs_hgnc_curated_tfs.txt in pyscenic_pipeline.sh? thank you very much, if I have the honor to get your way, it will be very helpful to me. My email address is: 1412494896@qq.com

**Comment by nathanin** [comment]
Hi, we got that table from here: https://github.com/aertslab/pySCENIC/blob/master/resources/hs_hgnc_curated_tfs.txt 

Thanks!
